/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.veiw.splite;

/**
 *
 * @author Alisson
 */
public class SplitePane extends javax.swing.JPanel {

    private enum State{
        ORIGINAL, SPLIT, EDITED;
    }
    
    private State state = State.SPLIT;
    
    /**
     * Creates new form SplitePane
     */
    public SplitePane() {
        initComponents();
    }
    
    public SpliteImage getSpliteImage(){
        return this.spliteImage1;
    }
    
    public void updateState(){
        switch (state) {
            case SPLIT:
                spliteImage1.setDividerLocation(spliteImage1.getWidth() / 2);
                break;
            case ORIGINAL:
                spliteImage1.setDividerLocation(spliteImage1.getWidth());
                break;
            case EDITED:
                spliteImage1.setDividerLocation(0);
                break;
            default:
                throw new AssertionError();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        originalButton = new javax.swing.JButton();
        splitButton = new javax.swing.JButton();
        editedButton = new javax.swing.JButton();
        spliteImage1 = new br.univali.veiw.splite.SpliteImage();

        setBackground(new java.awt.Color(50, 50, 50));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(75, 75, 75), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 45));

        originalButton.setBackground(new java.awt.Color(50, 50, 50));
        originalButton.setText("Original");
        originalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originalButtonActionPerformed(evt);
            }
        });

        splitButton.setBackground(new java.awt.Color(50, 50, 50));
        splitButton.setText("Split");
        splitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitButtonActionPerformed(evt);
            }
        });

        editedButton.setBackground(new java.awt.Color(50, 50, 50));
        editedButton.setText("Editada");
        editedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(originalButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editedButton)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(originalButton)
                    .addComponent(splitButton)
                    .addComponent(editedButton))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.SOUTH);
        add(spliteImage1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void originalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originalButtonActionPerformed
        state = State.ORIGINAL;
        updateState();
    }//GEN-LAST:event_originalButtonActionPerformed

    private void splitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splitButtonActionPerformed
        state = State.SPLIT;
        updateState();
    }//GEN-LAST:event_splitButtonActionPerformed

    private void editedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editedButtonActionPerformed
        state = State.EDITED;
        updateState();
    }//GEN-LAST:event_editedButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editedButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton originalButton;
    private javax.swing.JButton splitButton;
    private br.univali.veiw.splite.SpliteImage spliteImage1;
    // End of variables declaration//GEN-END:variables
}
